### ISSUE TITLE
Emmet stopped working in the public facing website

### ISSUE THREAD

**Issue by dustin-page** [filearts/plunker_www#105]
Adding a CSS selector like ".container" and hitting Tab button no longer generates code.

Also entering "ul>li*3" and hitting Tab doesn't generate code.

**Comment by dfsq** [comment]
+1 I posted similar [issue](https://github.com/filearts/plunker/issues/134) but in the wrong repo. Emmet support is crucial, please fix it.

**Comment by ggoodman** [comment]
Please use https://next.plnkr.co/edit/ until I have a chance to track down why this suddenly stopped working.
