### ISSUE TITLE
Can I delete an anonymous Plunker?

### ISSUE THREAD

**Issue by orlein** [filearts/plunker_www#115]
Hello there, 
I have used Plunker for about 2 days as an anonymous user. And I accidentally delete all of my local temp files (perhaps my security system deleted it). So I lost my deletion authorization of my Plunker. Unfortunately, there is some reason not to open the source code in my anonymous Plunker.
Is there any way to delete anonymous Plunker link? I googled this, but I couldn't find how to. Please help me.

**Comment by ggoodman** [comment]
@orlein anonymous plunks can only be deleted while you maintain the session identifier in your browser's cache. This is designed as a convenience so that users can participate without needing to become registered users.

Why do you feel the need to delete your anonymous plunk?

**Comment by orlein** [comment]
@ggoodman It sounds like I can't do nothing about it... anyway, Because the plunker has some sensitive data from my company, which has some strict security rules. But if it couldn't be searched by Google or something, It seems to be okay to ignore the plunker. Thank you for the reply.

**Comment by ggoodman** [comment]
@orlein if you have some string that I could use to locate the plunk in the database, I can delete or sanitize it.

**Comment by orlein** [comment]
@ggoodman I don't know exactly what data or string snippets are in there. But the code has over 280,000 lines of single JavaScript object and short code for showing the data into grids and charts.
