### ISSUE TITLE
No plunks showing in My plunks.

### ISSUE THREAD

**Issue by abalter** [filearts/plunker_www#120]
I've tried four browsers (Chrome, FF, Edge, Brave) and my plunks to not show when I am logged in. [Others are having](http://plnkr.co/group?place=msg%2Fplunker%2FtflFs3aTaFM%2FQq14Ro3ABAAJ)  the same problem.

I have some links stored to my plunks, and almost all of them come up. And I show as the user for these plunks. However, when I go to My plunks, there is nothing there.

**Comment by JonathanNagy** [comment]
Same here.  I have plunks from several years ago and two I've worked on in the last few days.  I've on seen plunks on my plunks page once out of the 10+ times I've been to the site while working on the new plunks.  The only way I can get back to my current plunks is cached url in chrome.  My old plunks are totally unaccessible.

**Comment by ggoodman** [comment]
@abalter, can you share a link to a plunk that you created but that doesn't appear in your 'my plunks' listing? This will help me identify what might have gotten out of sync.

**Comment by abalter** [comment]
My plunks list was COMPLETELY EMPTY. However, they are now showing. So the problem seems to be fixed.

**Comment by lawlesscreation** [comment]
Seeing the same problem with embeds on http://mbenford.github.io/ngTagsInput/demos and when visiting https://plnkr.co/ directly. Seeing errors in the console such as:

```
Uncaught TypeError: (t.data || "").search is not a function
    at pmh (sh.1836a2a6d9443e6d814c8dfc.html:1)

GET https://shot.plnkr.co/EX0xz5.png?d=2018-05-16T01:00:30.025Z 503 ()
```

**Comment by lawlesscreation** [comment]
Seems to be working again now and no longer getting 503 errors in the console 👍

**Comment by ggoodman** [comment]
Great to hear. I realized this morning that my cluster was oversubscribed on resources and an important component was failing to start up. I've adjusted cluster resources and the issue should be resolved.

**Comment by slytimus** [comment]
I too am having the same issue. Only the most recent nine plunks are displaying. There used to be paging buttons at the bottom of the page but for some reason, no longer display. Does anyone know how to get access to older plunks? I have written quite a few over the years and it would be a significant setback not having the ability to retrieve them.
