### ISSUE TITLE
JavaScript not being refreshed

### ISSUE THREAD

**Issue by alowdon** [filearts/plunker_www#123]
I noticed that changes to JavaScript files do not seem to be recognised. Obviously this makes using Plunkr very frustrating.

Minimal repo is here: https://plnkr.co/edit/7P8BNyllU1SCl34VCleE

You can change the text in script.js that is used to replace the span text, but the change will never be recognised, either with an automatic refresh or by stopping and starting the Plunkr. I have reproduced on Chrome (78.0.3904.87) and Firefox (70.0.1).

If you open the dev console and disable the cache under the Network tab, it starts working again, which leads me to think it's a caching issue. This can be used as a workaround but shouldn't be necessary.

I first noticed the issue on 30/10/19; everything seemed to be working as expected before then.

**Comment by ggoodman** [comment]
This should be fixed as mentioned on twitter: https://twitter.com/plnkrco/status/1195172167849304064
