### ISSUE TITLE
Utility to post to plnkr

### ISSUE THREAD

**Issue by iliakan** [filearts/plunker_www#36]
Hello,

I'd like to make a tiny utility written in Node.JS that will submit directory contents to plunker, like https://github.com/defunkt/gist does for gist.

Is there anything that already does the job?

**Comment by ishandutta2007** [comment]
But this utility is not working, I am getting the following errors.
https://github.com/iliakan/plunk/issues/13

**Comment by iliakan** [comment]
Update your Node.JS to 6.x at least.
