### ISSUE TITLE
Tidy should ignore <script type="text/ng-template"> 

### ISSUE THREAD

**Issue by rcollette** [filearts/plunker_www#46]
Working with an angular example, tidy is munging my angular in page templates, placing spaces between most things.

    <script type="text/ng-template" id="tempTest">
      <input type="date" data-ng-model="TestDate" / >
    </script>

becomes

    <script type="text/ng-template" id="tempTest">
      < input type = "date"
      data - ng - model = "TestDate" / >
    </script>

**Comment by wrummler** [comment]
Same concern here. The beautifier should ignore ng-template script tag content (in the sense that it shouldn't push it through `js_beautify`, but it should still apply HTML beautification).

The `tag_complete` local in `Parser.get_tag` seems to be clean enough after building to simply `split` and check for `'type'` and its value. Then [this line](https://github.com/filearts/plunker_www/blob/a57df562eea1163b8ded7715fcfcea1ca43c83cb/assets/vendor/js-beautify/beautify-html.js#L405)

    } else if (tag_check === 'script') { //for later script handling

could become something like

    } else if (tag_check === 'script' &&
               ignored_script_types.indexOf(tag_attribute_type) === -1) { //for later script handling

where `ignored_script_types` is an array of strings defined somewhere (maybe even on the `options` parameter of `style_html`), and would include at least `'text/ng-template'`.

I think that's all that's necessary, but I haven't finished reading the beautification logic. @ggoodman (or another experienced contributor), is this a reasonable approach?

**Comment by wrummler** [comment]
@ggoodman I missed the fact that js-beautify is external to plunker, sorry. The latest js-beautify [takes care of this issue](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L460-L463):

    } else if (tag_check === 'script' &&
        (tag_complete.search('type') === -1 ||
        (tag_complete.search('type') > -1 &&
        tag_complete.search(/\b(text|application)\/(x-)?(javascript|ecmascript|jscript|livescript)/) > -1))) {

Unless there's some reason not to, plunker should probably use the latest version of js-beautify or another stable version with this script-type handling.

**Comment by ggoodman** [comment]
Fixed with 9db18e8efb91b17c11da735bfa4be6144feede2f. Thanks for this!
