### ISSUE TITLE
access to private plunks of others

### ISSUE THREAD

**Issue by rafszul** [filearts/plunker_www#56]
not quite sure if it's the corect place for this but i can access plunks set by owners as private
 
![czvcyym](https://cloud.githubusercontent.com/assets/2082824/5882428/50ce904e-a341-11e4-8afd-4ba479cc617f.png)

**Comment by ggoodman** [comment]
Hi @rafszul,

Private plunks are modeled after Github's 'secret' gists. In fact, 'secret'
gists used to be called 'private' gists. I have not made the switch in name.

In summary, anyone can view any plunk as long as they know the url. Only
public plunks appear on the front page and when other users view your list
of plunks. It is quite possible that in Plunker.NEXT you will have the
ability to create 'real' private plunks.

**Comment by rafszul** [comment]
thanks, yeah i could've guess that, sorry for trouble and false alarm ;-) keep up with great work take care

**Comment by ggoodman** [comment]
No problems at all. I really appreciate people taking the time to let me know what does and doesn't work for them. The more feedback the better as long as it stays constructive.
