### ISSUE TITLE
ui has no obvious way to report a security bug privately

### ISSUE THREAD

**Issue by oresmus** [filearts/plunker_www#69]
A user finding a possible security bug in plnkr.co might want to report it privately, to give the developer a chance to evaluate it and fix it before it becomes public knowledge and potentially harms other users.

But I am unable to find any guidance in the plnkr.co UI on how to report a bug in a non-public way.

**Comment by ggoodman** [comment]
You can contact me at filearts on gmail. Thanks for reaching out.
