### ISSUE TITLE
Use Bower as dependency backend

### ISSUE THREAD

**Issue by DaAwesomeP** [filearts/plunker_www#71]
Hi,
I really like how Plunker has a dependency manager. Since it is community managed, it actually has potential to be updated somewhat frequently unlike *coughjsfiddlecough*. However, it is a mashup of many CDNs, random version increments, and incorrect dependency version matching. If Bower were used behind the scenes, then this problem would be resolved. Any package in Bower would be available as they are released, with all releases and dependencies included.

**Comment by ggoodman** [comment]
Hi @DaAwesomeP, thanks for the suggestion. I have thoroughly explored using bower as a backend driver for this feature and concluded that it was not a good solution.

When I have the time, I will set up automatic package management via npm + npmcdn by @mjackson. NPM's couchdb endpoints make it easy to query for available packages and npmcdn makes it easy to serve files within a given packages tarball.
