### ISSUE TITLE
Embedding forces HTTPS

### ISSUE THREAD

**Issue by iH8** [filearts/plunker_www#72]
When visiting embed.plnkr.co over http protocol, the iframe's source points to run.plnkr.co using https protocol. This causes mixed content errors for requests which are hardcoded to http. I'de suggest using a protolless url for iframe source `//run.plnkr.co` instead of `https://run.plnkr.co`.

Was thrown for a loop when my urls without protocol started using https while i was using http and the assets i was trying to load failed because https for them wasn't available. :)

**Comment by wasimsikder1** [comment]
Good

**Comment by ggoodman** [comment]
@iH8 can you confirm that this is appropriately resolved?

**Comment by iH8** [comment]
Sorry for the late response, works like a charm now @ggoodman, thanks a million
