### ISSUE TITLE
Question: Intranet hosted Plunker, where the files are stored in Plunker

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [filearts/plunker_www#76]
Looking for setting up plunker within office environment, useful for workshops and training. 

Where does the files added/edited by the users stored? In MongoDB? or in File system, also how the versions are maintained. 

Thanks in advance.

**Comment by ggoodman** [comment]
Plunks are stored in MongoDB. Revisions are stored as the text diff (using Google's diff patch match) against the succeeding (next most recent) version.

The logic for this is at: https://github.com/filearts/plunker_api/blob/master/resources/plunks.coffee#L401-L428
