### ISSUE TITLE
Newer gists with 32 character gist_id does not work on plunker

### ISSUE THREAD

**Issue by rrag** [filearts/plunker_www#90]
Old gist: works
http://plnkr.co/edit/gist:b993d5fcc5c09dd66a6e?p=preview

[block](http://bl.ocks.org/rrag/b993d5fcc5c09dd66a6e), 

New gist: does not work
http://plnkr.co/edit/gist:dc853a365171d1770ada7ecc107d08de?p=preview

This is a valid [gist](https://gist.github.com/rrag/dc853a365171d1770ada7ecc107d08de) and it works on blocks
http://bl.ocks.org/rrag/dc853a365171d1770ada7ecc107d08de

**Comment by ggoodman** [comment]
Thanks for bringing this to my attention @rrag.

**Comment by rrag** [comment]
Thanks. That was fast!!!
